version: 2
jobs:
  app:
    docker:
      - image: node:10
    steps:
      - checkout
      - name: build
        run: |
          cd contact-requests-collector
          npm install
          node_modules/.bin/gulp compile
      - name: package
        run: |
          cd contact-requests-collector
          npm install
          node_modules/.bin/gulp package

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - app