version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: |
          cd contact-requests-collector
          npm install
          node_modules/.bin/gulp package
      - persist_to_workspace:
          root: /workspace/contact-requests-collector/
          paths:
            - build
  plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run: terraform plan

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - plan
