version: 2

jobs:
  # The build job
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Install local dependencies
          command: cd contact-requests-collector && npm install
      - run:
          name: Linting
          command: cd contact-requests-collector && node_modules/.bin/gulp lint
      - run:
          name: Compile
          command: cd contact-requests-collector && node_modules/.bin/gulp compile
      - run:
          name: Package
          command: cd contact-requests-collector && node_modules/.bin/gulp package

workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build