version: 2.0
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - run:
          name: build lambda
          command: |
            ls
            cd contact-requests-collector
            npm install
            node_modules/.bin/gulp package
