version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: |
          cd contact-requests-collector
          npm install
          node_modules/.bin/gulp package
  plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - run: terraform plan

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - plan
